# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-infra:
    uses: /ABHIJITNAYAK/infra-pipeline/.github/workflows/reusable-infra-pipeline.yml@main
